channels:
  - conda-forge
dependencies:
      - cxx-compiler
      - boost=1.82.0
      - fmt
      - gsl
      - make
      - lld=15.0.5
      - python
      - ipykernel 
      - jupyter_client
      - pip
      - pip:
        - matplotlib
